# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pool: new_agent
variables:
  path: '$(System.DefaultWorkingDirectory)/Parent_Module'

steps:
- task: TerraformInstaller@1
  displayName: terraform_install
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  displayName: terraform_init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: $(path)
    backendServiceArm: 'oct_WIF'
    backendAzureRmStorageAccountName: 'store10110'
    backendAzureRmContainerName: 'octcont'
    backendAzureRmKey: 'backup.tfstate'
- task: TerraformTask@5
  displayName: terraform_validate
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: $(path)

- task: TerraformTask@5
  displayName: terraform_plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: $(path)

