trigger:
  branches:
    include:
      - main
      - develop

pool: new_agent

variables:
  directory: '$(System.DefaultWorkingDirectory)/Parent_Module'
  service_connection: 'oct_new'

steps:
- task: TerraformInstaller@1
  displayName: terraform install
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: terraform_init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: $(directory)
    backendServiceArm: $(service_connection)
    backendAzureRmStorageAccountName: 'store101011'
    backendAzureRmContainerName: 'blobcont'
    backendAzureRmKey: 'backend.tfstate'

- task: TerraformTask@5
  displayName: terraform_Validate
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: $(directory)

- task: TerraformTask@5
  displayName: terraform_Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: $(directory)
    environmentServiceNameAzureRM: $(service_connection)


- task: TerraformTask@5
  displayName: terraform_apply
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Parent_Module'
    commandOptions: '--auto-approve'
    environmentServiceNameAzureRM: $(service_connection)