trigger: none

pool: new_agent

stages:
  - stage: Install_Terraform
    displayName: "Stage 1 - Install Terraform"
    jobs:
      - job: Install
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

  - stage: Terraform_Init_Validate
    displayName: "Stage 2 - Terraform Init + Validate"
    dependsOn: Install_Terraform
    jobs:
      - job: InitValidate
        steps:
          - task: TerraformTask@5
            displayName: "Terraform Init"
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Parent_Module'
              backendServiceArm: 'oct_new'
              backendAzureRmStorageAccountName: 'store101011'
              backendAzureRmContainerName: 'blobcont'
              backendAzureRmKey: 'backend.tfstate'

          - task: TerraformTask@5
            displayName: "Terraform Validate"
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Parent_Module'

  - stage: Terraform_Plan
    displayName: "Stage 3 - Terraform Plan"
    dependsOn: Terraform_Init_Validate
    jobs:
      - job: Plan
        steps:
          - task: TerraformTask@5
            displayName: "Terraform Plan"
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Parent_Module'
              environmentServiceNameAzureRM: 'oct_new'

  - stage: Terraform_Apply
    displayName: "Stage 4 - Terraform Apply"
    dependsOn: Terraform_Plan
    condition: succeeded()
    jobs:
      - job: Apply
        steps:
          - task: TerraformTask@5
            displayName: "Terraform Apply"
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Parent_Module'
              commandOptions: '--auto-approve'
              environmentServiceNameAzureRM: 'oct_new'
