trigger: none
pool: new_agent
steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  displayName: terraform_init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Parent_Module'
    backendServiceArm: 'oct_new'
    backendAzureRmStorageAccountName: 'store101011'
    backendAzureRmContainerName: 'blobcont'
    backendAzureRmKey: 'backend.tfstate'

- task: TerraformTask@5
  displayName: terraform_validate
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Parent_Module'

- task: TerraformTask@5
  displayName: terraform_plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Parent_Module'
    environmentServiceNameAzureRM: 'oct_new'

- task: TerraformTask@5
  displayName: terraform_apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Parent_Module'
    commandOptions: '--auto-approve'
    environmentServiceNameAzureRM: 'oct_new'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'destroy'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Parent_Module'
    environmentServiceNameAzureRM: 'oct_new'