trigger: none
pool: new_agent
steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Parent_Module'
    backendServiceArm: 'oct_new'
    backendAzureRmStorageAccountName: 'store101011'
    backendAzureRmContainerName: 'blobcont'
    backendAzureRmKey: 'backend.tfstate'

